// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rawmqjtjhnaqggzsqmqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhd21xanRqaG5hcWdnenNxbXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTY1NjEsImV4cCI6MjA2NjEzMjU2MX0.j51nTTWhYeimjYOUph3v64qcNdrE2pCHB_fRUx7pJmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);